<?php use \app\library\Menu; ?>
<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?= base() ?>">
                <strong>Задачик</strong>
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <?php if (!Auth::isLogged()): ?>
                    <li><?= Menu::link("/admin/login", 'Вход'); ?></li>
                <?php else: ?>
                    <li><?= Menu::link("/admin/logout", 'Выход') ?></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>