<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Default Layout</title>

    <!-- bootstrap core css -->
    <link href="/errors/css/bootstrap.min.css" rel="stylesheet">

    <!-- styles -->
    <link rel="stylesheet" href="/admin/app.css">

</head>
<body>
   <div class="container">
   	   <div style="margin-top: 30px;">
            <div class="row">
              <div class="col-md-12">
                <h1 style="font-size: 3em;">404 Страница не найдена!</h1>
                <small>Опаа! что то пошло не так ((</small>
                  <?php view_path(__FILE__); ?>
              </div>
              </div>
      </div>
   </div>

   <!-- scripts -->
   <script src="/admin/app.css"></script>
</body>
</html>